# ────────────────────────────────────────────────────────────
# Custom Theme for btop
# Made with Omarchist
# ────────────────────────────────────────────────────────────

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#DEDBC8"

# Main text color
theme[main_fg]="#0c0c14"

# Title color for boxes
theme[title]="#695815"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#005C32"

# Background color of selected item in processes box
theme[selected_bg]="#762b2f"

# Foreground color of selected item in processes box
theme[selected_fg]="#DEDBC8"

# Color of inactive/disabled text
theme[inactive_fg]="#a19f7f"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#005C32"

# Cpu box outline color
theme[cpu_box]="#762b2f"

# Memory/disks box outline color
theme[mem_box]="#762b2f"

# Net up/down box outline color
theme[net_box]="#762b2f"

# Processes box outline color
theme[proc_box]="#762b2f"

# Box divider line and small boxes line color
theme[div_line]="#005C32"

# Temperature graph colors
theme[temp_start]="#4B0304"
theme[temp_mid]="#2E311A"
theme[temp_end]="#005C32"

# CPU graph colors
theme[cpu_start]="#4B0304"
theme[cpu_mid]="#2E311A"
theme[cpu_end]="#005C32"

# Mem/Disk free meter
theme[free_start]="#4B0304"
theme[free_mid]="#2E311A"
theme[free_end]="#005C32"

# Mem/Disk cached meter
theme[cached_start]="#4B0304"
theme[cached_mid]="#2E311A"
theme[cached_end]="#005C32"

# Mem/Disk available meter
theme[available_start]="#4B0304"
theme[available_mid]="#2E311A"
theme[available_end]="#005C32"

# Mem/Disk used meter
theme[used_start]="#4B0304"
theme[used_mid]="#2E311A"
theme[used_end]="#005C32"

# Download graph colors
theme[download_start]="#4B0304"
theme[download_mid]="#2E311A"
theme[download_end]="#005C32"

# Upload graph colors
theme[upload_start]="#4B0304"
theme[upload_mid]="#2E311A"
theme[upload_end]="#005C32"
