accent = "#005C32"
cursor = "#91760d"
foreground = "#0c0c14"
background = "#DEDBC8"
selection_foreground = "#91760d"
selection_background = "#0c0c14"

color0 = "#DEDBC8"
color1 = "#4B0304"
color2 = "#91760d"
color3 = "#2E311A"
color4 = "#005C32"
color5 = "#7a5e1e"
color6 = "#3B3B3B"
color7 = "#9E8B60"
color8 = "#262626"
color9 = "#4B0304"
color10 = "#91760d"
color11 = "#2E311A"
color12 = "#005C32"
color13 = "#7a5e1e"
color14 = "#3B3B3B"
color15 = "#9E8B60"
