accent = "#005C32"
cursor = "#91760d"
foreground = "#0c0c14"
background = "#DEDBC8"
selection_foreground = "#0c0c14"
selection_background = "#9a9078"

mode = "light"

selection = "#c4c1ac"
muted = "#665e4a"

hyprland_active_border = "rgb(2E311A)"
hyprland_inactive_border = "rgb(a89e86)"

dark_background = "#dedbc8"
darker_background = "#d5d2bf"
lighter_background = "#e9e6d3"

dark_foreground = "#5d5541"
light_foreground = "#2b2721"
bright_foreground = "#0c0c14"

red = "#4B0304"
yellow = "#2E311A"
orange = "#6c5319"
green = "#725c0a"
cyan = "#3B3B3B"
blue = "#005C32"
magenta = "#762b2f"
brown = "#4d3907"

bright_red = "#4B0304"
bright_yellow = "#005C32"
bright_green = "#725c0a"
bright_cyan = "#3B3B3B"
bright_blue = "#2E311A"
bright_magenta = "#762b2f"

color0 = "#DEDBC8"
color1 = "#4B0304"
color2 = "#725c0a"
color3 = "#2E311A"
color4 = "#005C32"
color5 = "#762b2f"
color6 = "#3B3B3B"
color7 = "#665e4a"
color8 = "#9a9078"
color9 = "#4B0304"
color10 = "#725c0a"
color11 = "#005C32"
color12 = "#2E311A"
color13 = "#762b2f"
color14 = "#3B3B3B"
color15 = "#0c0c14"
