# ────────────────────────────────────────────────────────────
# Custom Theme for Ghostty
# Made by Omarchist
# ────────────────────────────────────────────────────────────

background = #DEDBC8
foreground = #0c0c14

cursor-color = #91760d
cursor-text = #0c0c14

selection-background = #9a9078
selection-foreground = #0c0c14

# normal colors
palette = 0=#DEDBC8
palette = 1=#4B0304
palette = 2=#725c0a
palette = 3=#2E311A
palette = 4=#005C32
palette = 5=#762b2f
palette = 6=#3B3B3B
palette = 7=#665e4a

# bright colors
palette = 8=#9a9078
palette = 9=#4B0304
palette = 10=#725c0a
palette = 11=#005C32
palette = 12=#2E311A
palette = 13=#762b2f
palette = 14=#3B3B3B
palette = 15=#0c0c14
