-- Generated by hypr2lua-web.

hl.config({
  general = {
    col = {
      active_border = "rgb(7a5e1e)",
      inactive_border = "rgb(2E311A)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = "rgba(7a5e1eee)",
      border_inactive = "rgb(2E311A)",
    },
    groupbar = {
      col = {
        active = "rgba(7a5e1e99)",
        inactive = "rgba(2E311A88)",
      },
      text_color = "rgb(dfe4c4)",
      text_color_inactive = "rgba(dfe4c4ee)",
    },
  },
  decoration = {
    rounding = 2,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 16,
      color = "rgba(0, 0, 0, 0.2)",
    },
  },
})
