-- Generated by scripts/hypr2lua.
-- Source: /home/hancore/.config/omarchy/themes/whitegold/hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgb(7a5e1e)",
      inactive_border = "rgb(2E311A)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  decoration = {
    rounding = 2,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 16,
      color = "rgba(0, 0, 0, 0.2)",
    },
  },
})
