-- Generated by hypr2lua-web.

hl.config({
  general = {
    col = {
      active_border = "rgb(2E311A)",
      inactive_border = "rgb(a89e86)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = "rgba(2E311Aee)",
      border_inactive = "rgb(a89e86)",
    },
    groupbar = {
      col = {
        active = "rgba(005C3299)",
        inactive = "rgba(2E311A88)",
      },
      text_color = "rgb(DEDBC8)",
      text_color_inactive = "rgba(DEDBC8ee)",
    },
  },
  decoration = {
    rounding = 2,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 16,
      color = "rgba(0, 0, 0, 0.2)",
      color_inactive = "rgba(0, 0, 0, 0.1)",
    },
  },
})
