# ────────────────────────────────────────────────────────────
# Custom Theme for Kitty
# Made with Omarchist
# ────────────────────────────────────────────────────────────

## name: Custom Theme

foreground              #0c0c14
background              #DEDBC8
selection_background    #9a9078
selection_foreground    #0c0c14

cursor                  #91760d
cursor_text_color       #0c0c14

# URL underline color when hovering with mouse
url_color               #0c0c14

# Tab bar colors
active_tab_foreground   #0c0c14
active_tab_background   #DEDBC8
inactive_tab_foreground #0c0c14
inactive_tab_background #DEDBC8
tab_bar_background      #0c0c14

color0  #DEDBC8
color8  #9a9078
color1  #4B0304
color9  #4B0304
color2  #725c0a
color10 #725c0a
color3  #2E311A
color11 #005C32
color4  #005C32
color12 #2E311A
color5  #762b2f
color13 #762b2f
color6  #3B3B3B
color14 #3B3B3B
color7  #665e4a
color15 #0c0c14
